"""Exposes a URL that specifies the behaviour of this scalar."""
directive @specifiedBy(
  """The URL that specifies the behaviour of this scalar."""
  url: String!
) on SCALAR

"""Indicates an Input Object is a OneOf Input Object."""
directive @oneOf on INPUT_OBJECT

type ClientFilterInfo {
  id: String
  label: String
  uuids: String
}

type ClientInfo {
  baseCurrency: String
  file: String
  id: String
  label: String
}

type DeltaPoint {
  date: String
  value: MoneyInfo
}

"""A 64-bit signed integer"""
scalar Long

type MoneyInfo {
  amount: Float!
  currencyCode: String
}

"""Mutation root"""
type Mutation {
  updateQuotes(clientId: String, scope: UpdateQuotesScope): UpdateQuotesResult
}

type PortfolioSecurityPerformanceInfo {
  delta: MoneyInfo
  deltaPercent: Float!
  portfolioId: String
  portfolioName: String
  referenceAccountId: String
  referenceAccountName: String
  securities: [SecurityPerformanceInfo]
  startValue: MoneyInfo
}

"""Query root"""
type Query {
  clientFilterAccumulatedDelta(filterId: String, portfolioId: String, clientId: String, endDate: String, securityId: String, startDate: String): [DeltaPoint]
  clients: [ClientInfo]
  clientFilterDelta(filterId: String, clientId: String, endDate: String, startDate: String): MoneyInfo
  portfolioSecurityPerformance(filterId: String, clientId: String, endDate: String, startDate: String): [PortfolioSecurityPerformanceInfo]
  clientFilters(clientId: String): [ClientFilterInfo]
}

type QuoteUpdateProgress {
  completedTaskCount: Int!
  taskCount: Int!
  timestamp: Long!
}

type SecurityPerformanceInfo {
  delta: MoneyInfo
  deltaPercent: Float!
  securityId: String
  securityName: String
  startValue: MoneyInfo
}

"""Subscription root"""
type Subscription {
  quoteUpdates(clientId: String): QuoteUpdateProgress
}

type UpdateQuotesResult {
  scheduled: Boolean!
  securityCount: Int!
}

enum UpdateQuotesScope {
  ACTIVE
  ALL
  HOLDINGS
}

